### PR TITLE
Modify Gem File to include tzinfo-data for windows users

### PR DESCRIPTION
**Pull request by jakeoverall**
This will avoid the common error of the rails server not working on a windows environment due to the timezone error. 

Also Windows stable build for ruby is 2.0.0 so this will need to be changed in the gem file for windows users. I don't believe it should cause any problems it fires up just fine on my machine. 

Non Windows users just need to change the ruby version in the gem file back to 2.1.2

### CODE REVIEW

**Comment by sandlbn** [comment]
Hmm, probably for windows users  is better to use Virtual Machines, Vagrant etc ? I can create vagrant box with latest ruby and rails  and with vim or emacs.  I don't think that's the good idea to merge this push.

**Comment by mbmjertan** [comment]
Use VMs. They're easy to use and guarantee that you won't have OS-related problems.

I recommend Ubuntu Server 14.04

**Comment by tomohitoy** [comment]
@sandlbn 
It is so helpful for us to make vagrant-box for developing Marid.
Would you please make that?

**Comment by sandlbn** [comment]
@tomohitoy,
Yes that's no problem.

**Comment by sandlbn** [comment]
when vagrant box is ready I'm closing this ticket

**Pull request closed without merging**
